### PR TITLE
Added abuse method

### PR DESCRIPTION
**Pull request by shuttlesworthNEO**

### CODE REVIEW

**Comment by shuttlesworthNEO** [comment]
Hey! Why are the integration checks failing?

**Comment by dimple1024** [comment]
sir i just upgraded the paralleldots package installed in my system but i
am still getting the import error!
Please help!

**Comment by Meghdeep** [comment]
Could you please show us the entire error message ?

**Comment by dimple1024** [comment]
i have the screenshot of error herewith.

**Pull request closed without merging**
